[configuration]
# Can be "server", "client", or "singleplayer"
environment = "singleplayer"
# Can be "true" or "false"
debug = "true"
# Address to start endpoint, or to conect to depending on environment
connection_address = "127.0.0.1:2360"

[gameboard]
width = 25
height = 25
scale = 1.0

[server]
# Must be between 2 and 4
max_players = 2

[client]
username = "AuroraEchoes"
